### ISSUE TITLE
Solve Recover a secret string from random triplets Chalenge Codewars

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/Recover-a-secret-string-from-random-triplets#1]
https://www.codewars.com/kata/52c31f8e6605bcc646000082/train/javascript

**Comment by faeze-amn** [comment]
@FarshadJanmohammadi 
میتونید بگین چی می خواد چون مثال ققط یکی زده 
متوجه نمیشم چی می خواد
